(package "codemetrics"
         "0.1.0"
         "Plugin shows complexity information")

(website-url "https://github.com/jcs-elpa/codemetrics")
(keywords "complexity")

(package-file "codemetrics.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source 'gnu)
(source 'melpa)

(depends-on "emacs" "26.1")
(depends-on "tree-sitter")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
